name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  
        cache: 'npm' 

    - name: Install dependencies
      run: npm install
      working-directory: TrackTuner/track-tuner  
    - name: Start application
      run: npm start
      working-directory: TrackTuner/track-tuner  
